// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjHaLQN9aWijLsScdtQLbg1tUITnK2ZE',
    appId: '1:958640077345:web:40166f64efe57422c08160',
    messagingSenderId: '958640077345',
    projectId: 'mobile-app-project-60608',
    authDomain: 'mobile-app-project-60608.firebaseapp.com',
    storageBucket: 'mobile-app-project-60608.firebasestorage.app',
    measurementId: 'G-DM1WHGE4CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHitmJrKZ_CJrqMiz1q8geeGLp44JseNI',
    appId: '1:958640077345:android:bba765991ba7eda6c08160',
    messagingSenderId: '958640077345',
    projectId: 'mobile-app-project-60608',
    storageBucket: 'mobile-app-project-60608.firebasestorage.app',
  );
}
